CC = $(CROSS_COMPILE)gcc
AS = $(CROSS_COMPILE)gcc
LD = $(CROSS_COMPILE)gcc
AR = $(CROSS_COMPILE)ar
LD = $(CROSS_COMPILE)ld

ASSEMBLY_SYMBOL ?= ASSEMBLY

CFLAGS := -O0 -g

ASFLAGS := -D$(ASSMEMBLY_SYMBOL)

ARFLAGS := Drs
