CC = $(CROSS_COMPILE)gcc
AS = $(CROSS_COMPILE)gcc
LD = $(CROSS_COMPILE)ld
AR = $(CROSS_COMPILE)ar

ASSEMBLY_SYMBOL ?= ASSEMBLY

CFLAGS := -O0 -g

ASFLAGS := -D$(ASSEMBLY_SYMBOL)

ARFLAGS := Drs
AROPS_FILE := $(OUTDIR)/.arops

ifdef TARGET_ARCH
LD_SCRIPT ?= $(WORKSPACE_LOC)/script/ld/$(TARGET_ARCH)-$(TARGET_BOARD)-$(TARGET_SYSTEM)-$(LOAD_TYPE).lds
endif

ifdef LD_SCRIPT
LDFLAGS += -T $(LD_SCRIPT)
endif

LDOPS_FILE := $(OUTDIR)/.ldops
