#define VCPU_FPCR                VCPU_FPU_BASE            // Floating-point Control Register 
#define VCPU_FPSR                (VCPU_FPU_BASE + 1)      // Floating-point Status Register 
#define VCPU_FPEXC32_EL2         (VCPU_FPU_BASE + 2)      // Floating-point Exception Control Register
#define VCPU_Q0                  (VCPU_FPU_BASE + 3)
#define VCPU_Q1                  (VCPU_FPU_BASE + 5)
#define VCPU_Q2                  (VCPU_FPU_BASE + 7)
#define VCPU_Q3                  (VCPU_FPU_BASE + 9)
#define VCPU_Q4                  (VCPU_FPU_BASE + 11)
#define VCPU_Q5                  (VCPU_FPU_BASE + 13)
#define VCPU_Q6                  (VCPU_FPU_BASE + 15)
#define VCPU_Q7                  (VCPU_FPU_BASE + 17)
#define VCPU_Q8                  (VCPU_FPU_BASE + 19)
#define VCPU_Q9                  (VCPU_FPU_BASE + 21)
#define VCPU_Q10                 (VCPU_FPU_BASE + 23)
#define VCPU_Q11                 (VCPU_FPU_BASE + 25)
#define VCPU_Q12                 (VCPU_FPU_BASE + 27)
#define VCPU_Q13                 (VCPU_FPU_BASE + 29)
#define VCPU_Q14                 (VCPU_FPU_BASE + 31)
#define VCPU_Q15                 (VCPU_FPU_BASE + 33)
#define VCPU_Q16                 (VCPU_FPU_BASE + 35)
#define VCPU_Q17                 (VCPU_FPU_BASE + 37)
#define VCPU_Q18                 (VCPU_FPU_BASE + 39)
#define VCPU_Q19                 (VCPU_FPU_BASE + 41)
#define VCPU_Q20                 (VCPU_FPU_BASE + 43)
#define VCPU_Q21                 (VCPU_FPU_BASE + 45)
#define VCPU_Q22                 (VCPU_FPU_BASE + 47)
#define VCPU_Q23                 (VCPU_FPU_BASE + 49)
#define VCPU_Q24                 (VCPU_FPU_BASE + 51)
#define VCPU_Q25                 (VCPU_FPU_BASE + 53)
#define VCPU_Q26                 (VCPU_FPU_BASE + 55)
#define VCPU_Q27                 (VCPU_FPU_BASE + 57)
#define VCPU_Q28                 (VCPU_FPU_BASE + 59)
#define VCPU_Q29                 (VCPU_FPU_BASE + 61)
#define VCPU_Q30                 (VCPU_FPU_BASE + 63)
#define VCPU_Q31                 (VCPU_FPU_BASE + 65)
